name: Run tests and Sonarcloud scan

run-name: Test ${{ github.head_ref || github.ref }}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test-dev:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run build, Tests, Configure AWS
        uses: ./.github/actions/build-and-tests
        with:
          ref: ${{ github.ref }}
          aws_credentials: ${{ secrets.AWS_CREDENTIALS }}
          aws_config: ${{ secrets.AWS_CONFIG }}
